CREATE DATABASE Test;

USE Test;

CREATE TABLE User (
    UserID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    UserName VARCHAR(255) NOT NULL,
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL,
    PRIMARY KEY(UserID)
);
